steps:
    # Step to build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '-t'
          - 'gcr.io/$PROJECT_ID/my-app'
          - '.'

    # Push the Docker image to Google Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - 'gcr.io/$PROJECT_ID/my-app'

    # Deploy to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'run',
              'deploy',
              'my-app',
              '--image',
              'gcr.io/$PROJECT_ID/my-app',
              '--region',
              'us-central1',
              '--platform',
              'managed',
              '--quiet',
              '--allow-unauthenticated',
          ]

images:
    - 'gcr.io/$PROJECT_ID/my-app'

# Logging configuration
options:
    logging: 'NONE' # Logs only in Cloud Logging
    # Or, you could use:
    # logging: 'NONE'  # To disable logging altogether

# Optionally, specify the service account to use
serviceAccount: 'firebase-adminsdk-fbsvc@personal-2025-e1099.iam.gserviceaccount.com'
