steps:
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: bash
      args:
          - -c
          - |
              echo "⚙️  Building Docker Image with Secret Manager values..."
              docker build \
                --build-arg GCP_PROJECT_ID=$$GCP_PROJECT_ID \
                --build-arg GCP_SERVICE_ACCOUNT_EMAIL=$$GCP_SERVICE_ACCOUNT_EMAIL \
                --build-arg GCP_PRIVATE_KEY="$$GCP_PRIVATE_KEY" \
                -t gcr.io/$PROJECT_ID/mrkw .

      secretEnv:
          ['GCP_PROJECT_ID', 'GCP_SERVICE_ACCOUNT_EMAIL', 'GCP_PRIVATE_KEY']

images:
    - 'gcr.io/personal-2025-e1099/mrkw'

availableSecrets:
    secretManager:
        - versionName: projects/personal-2025-e1099/secrets/GCP_PROJECT_ID/versions/latest
          env: 'GCP_PROJECT_ID'
        - versionName: projects/personal-2025-e1099/secrets/GCP_SERVICE_ACCOUNT_EMAIL/versions/latest
          env: 'GCP_SERVICE_ACCOUNT_EMAIL'
        - versionName: projects/personal-2025-e1099/secrets/GCP_PRIVATE_KEY/versions/latest
          env: 'GCP_PRIVATE_KEY'

options:
    logging: CLOUD_LOGGING_ONLY
timeout: 1200s
